name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=$(git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1)-$(git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1) >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        run: |
          git clone --recursive https://github.com/theos/theos $GITHUB_WORKSPACE/theos
          export THEOS=$GITHUB_WORKSPACE/theos
          mkdir -p $THEOS/sdks
          curl -fsSL https://github.com/theos/sdks/archive/master.tar.gz | tar xz --strip-components=1 -C $THEOS/sdks
      
          # Debug: Check if Makefile exists
          ls -l $THEOS
          cat $THEOS/Makefile || echo "Makefile not found"
          
      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: "Package built for amd64"
          path: ${{ github.workspace }}/packages/*.deb
